<?php
/**
 * LiteMage
 * @package   LiteSpeed_LiteMage
 * @copyright  Copyright (c) LiteSpeed Technologies, Inc. All rights reserved. (https://www.litespeedtech.com)
 * @license     https://opensource.org/licenses/GPL-3.0
 */
?>

<?php if ($block->needAjax()):?>
<script>
var shouldReload = function(){
    if (document.cookie.indexOf('litemage-custvary') == -1) {
        fetch('<?php echo $block->getCheckUrl();?>', {
            method: 'POST',
        })
        .then(response => response.json())
        .then(data => {
            if (data.ajaxReload) {
                window.location.reload(true);
            }
        });
        return false;
    }
};

if (document.readyState === "complete" || (document.readyState !== "loading" && !document.documentElement.doScroll)) {
    shouldReload();
} else {
    document.addEventListener("DOMContentLoaded", shouldReload);
}
</script>
<?php endif?>
