<?php
/**
 * LiteMage
 * @package   LiteSpeed_LiteMage
 * @copyright  Copyright (c) LiteSpeed Technologies, Inc. All rights reserved. (https://www.litespeedtech.com)
 * @license     https://opensource.org/licenses/GPL-3.0
 */
?>

<?php
if ($block->canShowButton()):
?>
<br>
<div class="additional-cache-management">
    <h2>
        <span><?php echo $block->escapeHtml(__('LiteMage Cache Status (LiteSpeed Web Server)')); ?></span>
    </h2>
    <p>
        <?php echo $block->escapeHtml(__('Cache Warmer: ')); ?>
        <strong><?php echo $block->escapeHtml($block->isWarmupEnabled() ? __('Enabled') : __('Disabled')); ?></strong>
        <span style="display: inline-block; margin-left: 14px;">
            <a href="<?php echo $block->escapeUrl($block->getWarmupStatusUrl()); ?>">
                <?php echo $block->escapeHtml(__('Status')); ?>
            </a>
        </span>
        <span style="display: inline-block; margin-left: 10px;">
            <a href="<?php echo $block->escapeUrl($block->getWarmupConfigUrl()); ?>">
                <?php echo $block->escapeHtml(__('Configuration')); ?>
            </a>
        </span>
    </p>
</div>
<?php


if ($stats = $block->getCacheStatistics()) :
	?>

<div><table class="data-grid">
    <tr>
        <th class="data-grid-th" width="40%"><?php echo $block->escapeHtml(__('LiteMage Plan'));?></th>
		<th class="data-grid-th" width="20%"><?php echo $block->escapeHtml(__('Public Cache Hits')); ?></th>
		<th class="data-grid-th" width="20%"><?php echo $block->escapeHtml(__('LiteMage Cached Objects')); ?></th>
        <th class="data-grid-th" width="20%"><?php echo $block->escapeHtml(__('Not Cached (Limited by Plan)')); ?></th>
	</tr>
	<?php
		$severity = $stats['LITEMAGE_LIMITED'] > 0 ? 'grid-severity-critical' : 'grid-severity-notice';
		$noteclass = 'notifications-entry-description';
	?>
    <tr>
        <td>
            <div class="<?php echo $block->escapeHtmlAttr($severity); ?>">
                <?php echo $block->escapeHtml(__('Current Plan: ')); ?>
                <?php echo $block->escapeHtml($stats['plan']); ?>
            </div>
            <br>
            <div class="<?php echo $block->escapeHtmlAttr($noteclass); ?>">
                <?php echo $block->escapeHtml(__('Available Options')); ?>
            </div>
            <?php echo $block->escapeHtml(__('LiteMage Starter')); ?>
            <div class="<?php echo $block->escapeHtmlAttr($noteclass); ?>">
                <?php echo $block->escapeHtml(__('1,500 publicly cached objects')); ?>
            </div>
            <?php echo $block->escapeHtml(__('LiteMage Standard')); ?>
            <div class="<?php echo $block->escapeHtmlAttr($noteclass); ?>">
                <?php echo $block->escapeHtml(__('25,000 publicly cached objects')); ?>
            </div>
            <?php echo $block->escapeHtml(__('LiteMage Unlimited')); ?>
            <div class="<?php echo $block->escapeHtmlAttr($noteclass); ?>">
                <?php echo $block->escapeHtml(__('unlimited publicly cached objects')); ?>
            </div>
        </td>
        <td>
            <?php echo $block->escapeHtml($stats['PUB_HITS']); ?>
            <br><br>
            <?php echo $block->escapeHtml(__('Number of requests that hit public cache since last Flush All')); ?>
        </td>
        <td>
            <?php echo $block->escapeHtml($stats['LITEMAGE_OBJS']); ?>
            <br><br>
            <?php echo $block->escapeHtml(__('Current count of publicly cached objects')); ?>
        </td>
        <td>
            <div class="<?php echo $block->escapeHtmlAttr($severity); ?>">
                <?php echo $block->escapeHtml($stats['LITEMAGE_LIMITED']); ?>
            </div>
            <br>
            <?php echo $block->escapeHtml(__('Number of requests not served from cache due to plan limitation. You should upgrade your LiteMage plan if this value is not 0.')); ?>
        </td>
    </tr>
	</table>
	</div>

<?php
endif;
?>

<?php

endif;

?>
